# Generated by Django 4.2.2 on 2023-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0003_alter_vertriebangebot_ablehnungs_grund_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="anrede",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Familie", "Familie"),
                    ("Firma", "Firma"),
                    ("Herr", "Herr"),
                    ("Frau", "Frau"),
                ],
            ),
        ),
    ]
