# Generated by Django 4.2.2 on 2023-06-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0004_alter_vertriebangebot_anrede"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="ausrichtung",
            field=models.CharField(
                choices=[("Süd", "Süd"), ("Ost/West", "Ost/West")],
                default="Ost/West",
                max_length=10,
            ),
        ),
    ]
