# Generated by Django 4.2.2 on 2023-06-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0007_alter_vertriebangebot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="anrede",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Familie", "Familie"),
                    ("Firma", "Firma"),
                    ("Herr", "Herr"),
                    ("Herr Dr.", "Herr Dr."),
                    ("Frau", "Frau"),
                ],
            ),
        ),
    ]
