# Generated by Django 4.2.2 on 2023-06-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="imei",
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="sim_pin",
            field=models.SmallIntegerField(null=True, unique=True),
        ),
    ]
