# Generated by Django 4.2.2 on 2023-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_imei_alter_user_sim_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="anbieter",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_account",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_passwort",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="imei",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="sim_pin",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
