# Generated by Django 4.2.2 on 2023-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_alter_user_anbieter_alter_user_google_account_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sonstiges",
            field=models.TextField(blank=True, null=True),
        ),
    ]
