# Generated by Django 4.2.2 on 2023-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_user_zoho_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="zoho_data_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
